recipe/meta.yaml, recipe/upload_or_check_non_existence.py
Checklist
Fixes https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/12
=> Fix checking distribution exists

recipe/meta.yaml, recipe/run_conda_forge_build_setup_linux
=> Fix CONDA_BLD_PATH temporarily

recipe/meta.yaml, recipe/run_conda_forge_build_setup_linux, recipe/run_conda_forge_build_setup_osx, recipe/run_conda_forge_build_setup_win.bat
Adding this as it is requested information in the `conda` issue tracker template. Figure we should just add this to the build logs to improve the issue reporting experience with upstream.
cc @kalefranz @msarahan @conda-forge/core
Checklist
=> Run  `conda list --show-channel-urls`

recipe/conda_forge_ci_setup/upload_or_check_non_existence.py, recipe/meta.yaml
=> Fix upload for build number clobberered recipes

recipe/conda_forge_ci_setup/build_utils.py, recipe/conda_forge_ci_setup/upload_or_check_non_existence.py, recipe/meta.yaml
=> Variant files are a list.

recipe/conda_forge_ci_setup/__init__.py, recipe/conda_forge_ci_setup/build_utils.py, recipe/meta.yaml, recipe/setup.py
Fixes https://github.com/conda-forge/conda-smithy/issues/878
Checklist
=> Fix upload_global_config not actually opening the file

recipe/meta.yaml, recipe/run_conda_forge_build_setup_osx
=> We want to be able to force this for azure-pipelines as well

.appveyor.yml, .azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, recipe/conda_forge_ci_setup/upload_or_check_non_existence.py, recipe/meta.yaml
=> Azure sends secrets in a somewhat different way than the other CIs

recipe/conda_forge_ci_setup/build_utils.py, recipe/meta.yaml
This saves a lot of time on CI
=> No build number clobber needed anymore

recipe/conda_forge_ci_setup/upload_or_check_non_existence.py, recipe/meta.yaml
=> Added try and backoff to uploading of artifacts

recipe/meta.yaml, recipe/run_conda_forge_build_setup_linux, recipe/run_conda_forge_build_setup_osx
=> Activate env variables

.appveyor.yml, .circleci/build_steps.sh, .travis.yml, recipe/conda_forge_ci_setup/build_utils.py, recipe/conda_forge_ci_setup/upload_or_check_non_existence.py, recipe/meta.yaml
=> retry upload

recipe/conda_forge_ci_setup/upload_or_check_non_existence.py
=> Actually fail the upload if we failed

recipe/conda_forge_ci_setup/build_utils.py, recipe/meta.yaml
=> Only allow conda-forge and defaults if uploading to conda-forge

recipe/meta.yaml, recipe/run_conda_forge_build_setup_linux
=> Fix CI being unbounded

recipe/meta.yaml, recipe/run_conda_forge_build_setup_linux
Fixes https://github.com/conda-forge/conda-smithy/issues/1179
Checklist
=> Use feedstock_root env variable

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_aarch64_python3.6.____cpython.yaml, .ci_support/linux_aarch64_python3.7.____cpython.yaml, .ci_support/linux_ppc64le_python3.6.____cpython.yaml, .ci_support/linux_ppc64le_python3.7.____cpython.yaml, .ci_support/linux_python3.6.____cpython.yaml, .ci_support/linux_python3.7.____cpython.yaml, .ci_support/osx_python3.6.____cpython.yaml, .ci_support/osx_python3.7.____cpython.yaml, .ci_support/win_python3.6.____cpython.yaml, .ci_support/win_python3.7.____cpython.yaml, README.md, recipe/meta.yaml, recipe/run_conda_forge_build_setup_win.bat
Port the changes from `climlab` here to fix Fortran packages on Windows.
=> Remove gfortran

.azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .scripts/build_steps.sh, recipe/conda_forge_ci_setup/build_utils.py, recipe/meta.yaml
Checklist
cc @CJ-Wright, @beckermr
=> Override upload_or_check_non_existence.py

recipe/meta.yaml, recipe/run_conda_forge_build_setup_win.bat
=> Remove some paths

recipe/meta.yaml, recipe/run_conda_forge_build_setup_win.bat
=> Remove C:\hostedtoolcache paths again

recipe/conda_forge_ci_setup/upload_or_check_non_existence.py, recipe/meta.yaml
=> upload all built packages, except for the excluded ones

.azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .scripts/build_steps.sh, recipe/conda_forge_ci_setup/upload_or_check_non_existence.py, recipe/meta.yaml
=> BUG use the full path

recipe/conda_forge_ci_setup/mangle_homebrew.py, recipe/meta.yaml, recipe/setup.py
=> ENH add script to mangle homebrew

recipe/conda_forge_ci_setup/mangle_homebrew.py, recipe/meta.yaml
=> BUG make sure to put entry point in

.azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .scripts/run_docker_build.sh, recipe/meta.yaml, recipe/run_conda_forge_build_setup_win.bat
Checklist
See discussion [here](https://github.com/conda-forge/cryptography-feedstock/pull/37#issuecomment-619308180).
=> delete libcrypto & libssl from C:\Windows\System32 [2.x]

recipe/meta.yaml, recipe/run_conda_forge_build_setup_win.bat
Checklist
Same as #84; as [requested](https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/84#issuecomment-619539923)
=> delete libcrypto & libssl from C:\Windows\System32 [master]

.azure-pipelines/azure-pipelines-win.yml, .scripts/build_steps.sh, .scripts/run_docker_build.sh, .scripts/run_osx_build.sh, recipe/meta.yaml, recipe/run_conda_forge_build_setup_win.bat
=> Persist PATH changes

recipe/meta.yaml
=> Use m2-git as git on windows is broken

recipe/conda_forge_ci_setup/feedstock_outputs.py, recipe/meta.yaml
=> BUG use the sharded output name

recipe/conda_forge_ci_setup/feedstock_outputs.py, recipe/conda_forge_ci_setup/upload_or_check_non_existence.py, recipe/meta.yaml
=> BUG make sure to use only allowed dist names

.gitignore, recipe/conda_forge_ci_setup/build_utils.py, recipe/conda_forge_ci_setup/upload_or_check_non_existence.py, recipe/meta.yaml
=> Allow to upload privately

recipe/meta.yaml, recipe/run_conda_forge_build_setup_linux
=> Support ppc64le cuda

.scripts/build_steps.sh, .scripts/run_osx_build.sh, recipe/meta.yaml, recipe/run_conda_forge_build_setup_osx
=> BUG silly bug

.azure-pipelines/azure-pipelines-linux.yml, .drone.yml, .scripts/build_steps.sh, .travis.yml, README.md, conda-forge.yml, recipe/cross_compile_support.sh, recipe/download_osx_sdk.sh, recipe/meta.yaml, recipe/run_conda_forge_build_setup_linux, recipe/run_conda_forge_build_setup_osx
=> Add cross compile support

recipe/meta.yaml, recipe/run_conda_forge_build_setup_linux
=> Download the OSX SDK if MACOSX_DEPLOYMENT_TARGET set even for linux

recipe/cross_compile_support.sh, recipe/meta.yaml
=> Fix typo in cross_compile_support.sh

.scripts/build_steps.sh, recipe/cross_compile_support.sh, recipe/download_osx_sdk.sh, recipe/meta.yaml, recipe/run_conda_forge_build_setup_osx
=> BUG append to scripts properly

recipe/cross_compile_support.sh, recipe/meta.yaml
=> Set build_platform

recipe/conda_forge_ci_setup/upload_or_check_non_existence.py, recipe/meta.yaml
=> Look for cross compile folders too

recipe/download_osx_sdk.sh, recipe/meta.yaml
=> Deprecate WITH_LATEST_OSX_SDK and use MACOSX_SDK_VERSION

recipe/conda_forge_ci_setup/build_utils.py, recipe/meta.yaml
=> Allow uploading with conda-web in source channels

recipe/conda_forge_ci_setup/upload_or_check_non_existence.py, recipe/meta.yaml
=> don't try to copy packages in prod channel

recipe/conda_forge_ci_setup/feedstock_outputs.py, recipe/conda_forge_ci_setup/upload_or_check_non_existence.py, recipe/meta.yaml
=> REF pass comment on error flag

recipe/meta.yaml, recipe/run_conda_forge_build_setup_win.bat
=> windows strict channel priority

recipe/install_cuda.bat, recipe/meta.yaml
=> Install nsight_nvtx on cuda 11

recipe/download_osx_sdk.sh, recipe/meta.yaml
=> support drone cross osx

recipe/cross_compile_support.sh, recipe/meta.yaml
=> set QEMU_LD_PREFIX

recipe/cross_compile_support.sh, recipe/meta.yaml
=> Fix QEMU_LD_PREFIX

recipe/download_osx_sdk.sh, recipe/meta.yaml
=> simplify downloading sdk

recipe/install_cuda.bat, recipe/meta.yaml
xref: https://github.com/conda-forge/cudatoolkit-feedstock/pull/57#issuecomment-804063842
cc @mike-wendt @kkraus14 @jaimergp @leofang
Checklist
=> Update CUDA 11.2 to 11.2.2 on Windows

recipe/meta.yaml
Checklist
This is an update to release the fix from https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/149.
attn @jakirkham
=> REL: conda-forge-ci-setup v3.9.2

recipe/meta.yaml, recipe/run_conda_forge_build_setup_osx
=> Allow OSX_SDK_DIR to be overriden

recipe/meta.yaml, recipe/run_conda_forge_build_setup_win.bat
=> Remove msmpi in System32 as well

recipe/meta.yaml, recipe/run_conda_forge_build_setup_win.bat
Fixing a very likely mistake from #156 
CC @isuruf
=> Also copy SetPageFileSize.ps1

recipe/meta.yaml, recipe/run_conda_forge_build_setup_osx
=> Sanitize osx paths on azure

recipe/download_osx_sdk.sh
=> Enable using macOS 11.3 SDK

recipe/meta.yaml
=> need cctools to avoid apple tools

recipe/cross_compile_support.sh, recipe/meta.yaml
=> check for yum_requirements existence and use mamba

recipe/meta.yaml
=> allow boa 0.8

recipe/conda_forge_ci_setup/build_utils.py, recipe/meta.yaml, recipe/run_conda_forge_build_setup_osx
=> ENH fail if travis not on special arch

recipe/meta.yaml
=> relax boa constraint

.azure-pipelines/azure-pipelines-win.yml, .circleci/config.yml, recipe/meta.yaml, recipe/run_conda_forge_build_setup_win.bat
=> Remove vs2008 support

recipe/conda_forge_ci_setup/feedstock_outputs.py, recipe/meta.yaml
=> ENH move to sha256

recipe/install_cuda.bat, recipe/meta.yaml
xref: https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/216#discussion_r1037513019
cc @m3vaz
<hr>
Checklist
=> Fix `md5` for Windows CUDA 11.8 installer

recipe/conda_forge_ci_setup/upload_or_check_non_existence.py, recipe/meta.yaml
https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/219#discussion_r1037636897
Checklist
=> Fix extra whitespace in `--show-traceback` flag

recipe/conda_forge_ci_setup/build_utils.py, recipe/meta.yaml
Checklist
Instead of checking whether the string starts with the pattern, check for a full match.
cc/ @isuruf @beckermr
=> Fix `channel_sources` upload checks

recipe/download_osx_sdk.sh, recipe/meta.yaml
following #228 and #229
xref https://github.com/conda-forge/pytorch-cpu-feedstock/pull/162
Checklist
=> fix untarring osx SDKSs from recent PR

recipe/download_osx_sdk.sh, recipe/meta.yaml
I messed up in https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/230
Checklist
=> Fixup specifying the output filename in CURL

recipe/cross_compile_support.sh, recipe/meta.yaml
=> Install libcuda.so.1 to QEMU sysroot

recipe/meta.yaml
Checklist
Comes from https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/233#issuecomment-1536112503
=> Cut 3.31.0

recipe/cross_compile_support.sh, recipe/meta.yaml
This reverts commit ecd275ff5ddf58a064a8de51d2f345dfd505aa44.
Had no impact, see discussion in #252
=> Revert "install libcuda stub into QEMU-sysroot for testing in emulation"

recipe/install_cuda.bat, recipe/meta.yaml
cc: @jakirkham @h-vetinari for vis
Checklist
=> Fix CUDA Windows installer urls

recipe/meta.yaml
=> Fix mamba constraint

recipe/meta.yaml, recipe/run_conda_forge_build_setup_win.bat
=> [3.x] Support CUDA 12 + Windows

recipe/run_conda_forge_build_setup_osx
=> Fix OSX_SDK_DIR when building locally

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .scripts/build_steps.sh, .scripts/run_docker_build.sh, .scripts/run_osx_build.sh, .scripts/run_win_build.bat, README.md, recipe/cross_compile_support.sh, recipe/meta.yaml
Same as PR ( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/302 ) backported to the `3.x` branch.
<hr>
Checklist
=> Relax CUDA 12 check in cross-compilation (for 3.x)

recipe/download_osx_sdk.sh, recipe/meta.yaml
=> Revert "Set default MACOSX_DEPLOYMENT_TARGET to 10.13"

recipe/meta.yaml, recipe/run_conda_forge_build_setup_win.bat
=> update PATH sanitizing

recipe/cross_compile_support.sh, recipe/meta.yaml
From this [comment](https://github.com/conda-forge/faiss-split-feedstock/pull/75#issuecomment-2274895743); thank you @isuruf 🙏
=> ensure correct sysroot for cross-compilation with newer glibc

recipe/conda_forge_ci_setup/upload_or_check_non_existence.py
=> add import RATTLER_BUILD

recipe/conda_forge_ci_setup/feedstock_outputs.py, recipe/meta.yaml
=> feat: error if output fails validation according to global setting

recipe/cross_compile_support.sh, recipe/meta.yaml
=> Remove cdt_name usage now that cdt_name == conda

recipe/meta.yaml, recipe/run_conda_forge_build_setup_win.bat
Checklist
It's hard to write OR in CMD language.
=> Add a variable CONDA_SKIP_TESTS to skip tests in bld.bat

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_64_cuda_compilerNonecuda_compiler_versionNonemicroarch_level1python3.10.____cpython.yaml, .ci_support/linux_64_cuda_compilerNonecuda_compiler_versionNonemicroarch_level1python3.11.____cpython.yaml, .ci_support/linux_64_cuda_compilerNonecuda_compiler_versionNonemicroarch_level1python3.12.____cpython.yaml, .ci_support/linux_64_cuda_compilerNonecuda_compiler_versionNonemicroarch_level1python3.13.____cp313.yaml, .ci_support/linux_64_cuda_compilerNonecuda_compiler_versionNonemicroarch_level1python3.9.____cpython.yaml, .ci_support/linux_64_cuda_compilerNonecuda_compiler_versionNonemicroarch_level4python3.10.____cpython.yaml, .ci_support/linux_64_cuda_compilerNonecuda_compiler_versionNonemicroarch_level4python3.11.____cpython.yaml, .ci_support/linux_64_cuda_compilerNonecuda_compiler_versionNonemicroarch_level4python3.12.____cpython.yaml, .ci_support/linux_64_cuda_compilerNonecuda_compiler_versionNonemicroarch_level4python3.13.____cp313.yaml, .ci_support/linux_64_cuda_compilerNonecuda_compiler_versionNonemicroarch_level4python3.9.____cpython.yaml, .ci_support/linux_64_cuda_compilernvcccuda_compiler_version11.8microarch_level1python3.10.____cpython.yaml, .ci_support/linux_64_cuda_compilernvcccuda_compiler_version11.8microarch_level1python3.11.____cpython.yaml, .ci_support/linux_64_cuda_compilernvcccuda_compiler_version11.8microarch_level1python3.12.____cpython.yaml, .ci_support/linux_64_cuda_compilernvcccuda_compiler_version11.8microarch_level1python3.13.____cp313.yaml, .ci_support/linux_64_cuda_compilernvcccuda_compiler_version11.8microarch_level1python3.9.____cpython.yaml, .ci_support/linux_64_cuda_compilernvcccuda_compiler_version11.8microarch_level4python3.10.____cpython.yaml, .ci_support/linux_64_cuda_compilernvcccuda_compiler_version11.8microarch_level4python3.11.____cpython.yaml, .ci_support/linux_64_cuda_compilernvcccuda_compiler_version11.8microarch_level4python3.12.____cpython.yaml, .ci_support/linux_64_cuda_compilernvcccuda_compiler_version11.8microarch_level4python3.13.____cp313.yaml, .ci_support/linux_64_cuda_compilernvcccuda_compiler_version11.8microarch_level4python3.9.____cpython.yaml, .scripts/run_win_build.bat, README.md, recipe/conda_build_config.yaml, recipe/cross_compile_support.sh, recipe/get_x86_64_level.py, recipe/meta.yaml
=> support avx512 with emulation

recipe/meta.yaml, recipe/run_conda_forge_build_setup_win.bat
=> echo off at the end

recipe/cross_compile_support.sh, recipe/meta.yaml
=> print sysroot env info

recipe/cross_compile_support.sh, recipe/meta.yaml
=> ensure sysroot does not change
