conda-forge/conda-forge-ci-setup-feedstock

recipe/meta.yaml
recipe/run_conda_forge_build_setup_osx

Closes https://github.com/conda-forge/conda-smithy/issues/678
Configures `CONDA_BUILD_SYSROOT` dynamically on Travis CI as part of the build setup. Does this as we need to check for the active macOS SDK with `xcode-select -p`.
cc @isuruf

Set CONDA_BUILD_SYSROOT

---

.appveyor.yml
recipe/meta.yaml
recipe/upload_or_check_non_existence.py

Fixes https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/9
Seems `get_binstar` has been deprecated for a while (and recently removed). This switches us over to the newer, preferred `get_server_api`.
xref: https://github.com/Anaconda-Platform/anaconda-client/issues/463
xref: https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/94 (backport)

Use newer anaconda-client API

---

recipe/meta.yaml
recipe/run_conda_forge_build_setup_win.bat

Use `conda.exe` on Windows. Basically forward porting PR ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/96 ).
cc @isuruf @msarahan

Windows use conda.exe

---

recipe/meta.yaml
recipe/upload_or_check_non_existence.py

This is a refactor of the upload routines so that the token is
rendered once for all uploads. 
It uses list comprehensions to remove the nesting of the 
previous for-loops and conditional statements.
Checklist
Close #14

Refactor distribution upload code

---

recipe/conda_forge_ci_setup/build_utils.py

Fixes #25
If i bump the build number, this will conflict with #21 🐩 
Checklist

Fix the case where build number is sometimes a int.

---

recipe/meta.yaml
recipe/run_conda_forge_build_setup_osx

Rather than checking `if circleci`, check if the sdk is needed. This prepares for updating the Travis xcode image to a more recent version that will not have the aged 10.9 SDK available.
Additionally:
- inherit rather than override MACOSX_DEPLOYMENT_TARGET, to avoid overriding the new way to set this with the old way
- use plutil instead of sed to rewrite MinimumSDKVersion (more future-proof, works for binary plists, which current versions of xcode use, isn't sensitive to previous value)
The Travis image needs to be updated pretty soon: https://github.com/conda-forge/conda-forge.github.io/issues/641

Download mac sdk if not present

---

recipe/meta.yaml
recipe/run_conda_forge_build_setup_osx

The `DTSDKName` was getting fixed by our old `sed` strategy along with the `MinimumSDKVersion`. We fix the `MinimumSDKVersion` already as this vital. It's less clear if the `DTSDKName` needs to be accurately reflected. Though it could show up in applications' `Info.plist`, so we might as well have it accurately reflected just in case. After this change there does not appear to be any more references to the OS SDK version other than the intended one.
Checklist

Update `DTSDKName` to match our macOS SDK

---

recipe/conda_forge_ci_setup/upload_or_check_non_existence.py
recipe/meta.yaml

Since #44, pull requests builds are currently failing on platforms other than azure due to `BINSTAR_TOKEN` not being set. Example from [this](https://circleci.com/gh/conda-forge/uproot-feedstock/45) build:
```python
+ upload_package /home/conda/feedstock_root /home/conda/recipe_root /home/conda/feedstock_root/.ci_support/linux_python3.7.yaml
Traceback (most recent call last):
File "/opt/conda/bin/upload_package", line 11, in <module>
sys.exit(upload_package())
File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 764, in __call__
return self.main(*args, **kwargs)
File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 956, in invoke
return ctx.invoke(self.callback, …
```

Fix pull request failures

---

recipe/conda_forge_ci_setup/build_utils.py
recipe/meta.yaml

This is an alternative to https://github.com/conda-forge/conda-smithy/pull/1108
Instead of checking this in all CI scripts, the logic is moved to this script.

Check for UPLOAD_ON_BRANCH and GIT_BRANCH for uploading

---

recipe/meta.yaml
recipe/run_conda_forge_build_setup_linux

The CPU_COUNT on TravisCI should be two (2) and leads to killed compiler processes otherwise for some builds.
See: https://docs.travis-ci.com/user/reference/overview/
Addresses: https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/53#issuecomment-571796823
Checklist

TravisCI: CPU_COUNT is Two (2)

---

recipe/meta.yaml
recipe/run_conda_forge_build_setup_linux
recipe/run_conda_forge_build_setup_osx

Add strict priority for pypy builds

---

recipe/meta.yaml
recipe/run_conda_forge_build_setup_linux

When running Docker builds locally on Linux, the default behavior appends a blank line to the YAML configuration file needlessly, potentially polluting Git checkouts.
Checklist
This isn't worth building a new package for, so I'm not bumping the build number or anything.

ENH If possible, don't modify the config.yaml file on Linux

---

.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.scripts/build_steps.sh
.scripts/run_docker_build.sh
recipe/conda_forge_ci_setup/build_utils.py
recipe/conda_forge_ci_setup/feedstock_outputs.py
recipe/conda_forge_ci_setup/upload_or_check_non_existence.py
recipe/meta.yaml

It turns out that the CI services all use different names for the directory where the feedstock is checked out and that it is easier to simply have smithy compute the feedstock name rather than have this script guess it on the fly. Similarly, smithy is already checking the conda-forge.yml to see if validation should happen, so I moved all of that logic turning validation on into smithy and not here.
Checklist

ENH fix bugs in cfep-13 validation, simpler

---

.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
recipe/conda_forge_ci_setup/build_utils.py
recipe/conda_forge_ci_setup/upload_or_check_non_existence.py
recipe/meta.yaml

This PR unbreaks the API with v2 and uses the staging token if it is there. 
Checklist

ENH unbreak the API and use staging token

---

.azure-pipelines/azure-pipelines-linux.yml
.ci_support/linux_cuda_compiler_version10.0python3.6.____cpython.yaml
.ci_support/linux_cuda_compiler_version10.0python3.7.____cpython.yaml
.ci_support/linux_cuda_compiler_version10.1python3.6.____cpython.yaml
.ci_support/linux_cuda_compiler_version10.1python3.7.____cpython.yaml
.ci_support/linux_cuda_compiler_version10.2python3.6.____cpython.yaml
.ci_support/linux_cuda_compiler_version10.2python3.7.____cpython.yaml
.ci_support/linux_cuda_compiler_version9.2python3.6.____cpython.yaml
.ci_support/linux_cuda_compiler_version9.2python3.7.____cpython.yaml
.ci_support/linux_cuda_compiler_versionNonepython3.6.____cpython.yaml
.ci_support/linux_cuda_compiler_versionNonepython3.7.____cpython.yaml
README.md
recipe/meta.yaml
recipe/run_conda_forge_build_setup_linux

This is complementary to https://github.com/conda-forge/docker-images/pull/135; aiming at unblocking https://github.com/conda-forge/pyarrow-feedstock/pull/101 & https://github.com/conda-forge/faiss-split-feedstock/pull/1.

Add missing libcuda.so on 9.2

---

.scripts/build_steps.sh
.scripts/run_osx_build.sh
recipe/meta.yaml
recipe/run_conda_forge_build_setup_linux
recipe/run_conda_forge_build_setup_osx

Checklist
This PR turns on strict channel priority for linux on all builds. 
cc @isuruf @ocefpaf @conda-forge/core

ENH strict channel priority for linux

---

.gitignore
recipe/meta.yaml
recipe/run_conda_forge_build_setup_osx

Some projects require newer versions of the OSX SDK to be used, even
though the deployment target may be older. [Qt is one of those cases](https://doc.qt.io/qt-5/macos.html),
and using an older version of the OSX SDK to build Python, for instance,
[is causing some bugs when used with PySide2](https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/67).
Since Apple supports having an older deployment target while building
with a new SDK, default to the new SDK.
I am cautiously submitting this PR, without testing it, and knowing that
this might break some CI. But I am submitting it as a possible solution
to fix #67, which is causing problems for one of our projects.
Checklist
Fixes: #67

Use the latest SDK For macOS if specified

---

.gitignore
recipe/meta.yaml
recipe/run_conda_forge_build_setup_linux
recipe/run_conda_forge_build_setup_osx

Checklist
Allows the CPU_COUNT variable to be set manually as suggested in https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/53#issuecomment-484327013.

Allow CPU_COUNT to be set externally

---

recipe/download_osx_sdk.sh
recipe/meta.yaml
recipe/run_conda_forge_build_setup_osx

MacOSX11.0.sdk support

---

recipe/conda_forge_ci_setup/upload_or_check_non_existence.py

Workaround for Windows permission issues
Checklist

Don't fail if unable to remove temporary directory

---

recipe/install_cuda.bat
recipe/meta.yaml

add cuda 11.2.1 and make it default for cuda 11.2 builds

---

recipe/meta.yaml
recipe/run_conda_forge_build_setup_linux
recipe/run_conda_forge_build_setup_win.bat

Checklist
This PR adds `CONDA_OVERRIDE_CUDA` as discussed on Gitter. This will enable packages to specify `__cuda` versions as a run dependency.
I was able to test that the `shyaml` logic detects the correct values for `CONDA_OVERRIDE_CUDA`. See also: [conda docs on detected package overrides](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-virtual.html#overriding-detected-packages)).

Add CONDA_OVERRIDE_CUDA for current CUDA version.

---

recipe/conda_forge_ci_setup/build_utils.py

This is a proposed fix for the case when `~/.condarc` does not have the `defaults` channel and only has the `conda-forge` one (or any other). The problem was originally observed on the [OSX build](https://dev.azure.com/nsls2forge/nsls2forge/_build/results?buildId=7965&view=logs&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=20c71c51-4b27-578b-485d-06ade2de1d00&l=298) for https://github.com/nsls-ii-forge/hunter-feedstock/pull/8:
```py
Setting up the condarc and mangling the compiler.
+ setup_conda_rc ./ ./recipe ./.ci_support/osx_64_python3.7.yaml
CondaKeyError: 'channels': 'defaults' is not in the 'channels' key of the config file
Traceback (most recent call last):
File "/Users/runner/miniforge3/bin/setup_conda_rc", line 11, in <module>
sys.exit(setup_conda_rc())
File …
```

Do not raise an exception if 'defaults' is not in the config

---

recipe/meta.yaml
recipe/run_conda_forge_build_setup_linux
recipe/run_conda_forge_build_setup_osx
recipe/run_conda_forge_build_setup_win.bat

The `run_conda_forge_build_setup` scripts read from `conda-forge.yml` to get the `channel_priority`, defaulting to strict if the setting is missing. But if `conda-forge.yml` is missing completely, the script would fail because shyaml does not return the default when there is no YAML to parse at all. This fixes that by ensuring that "strict" is returned in those cases as well.
While `conda-forge.yml` would never normally be missing, if https://github.com/conda-forge/conda-smithy/pull/1469 is merged then it becomes possible to put the feedstock configuration in another file. If that is done, then the existing scripts will fail. With this fix, that change to `conda-smithy` becomes usable, even though it would be impossible to override `channel_priority` (possibilities for doing this could be …

Don't fail run_conda_forge_build_setup when conda-forge.yml missing

---

recipe/ExecuteSetPageFileSize.bat
recipe/SetPageFileSize.ps1
recipe/meta.yaml
recipe/run_conda_forge_build_setup_win.bat

As [mentioned](https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/157#issuecomment-875109296) in #157, something is still not working with resetting the pagefile size - or the 4GB are not enough for some reason.
In any case, the errors with `OSError: [WinError 1455] The paging file is too small for this operation to complete` are still occurring in the numpy feedstock (e.g. [this](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=350018&view=logs&j=171a126d-c574-5c8c-1269-ff3b989e923d&t=1183ba29-a0b5-5324-8463-2a49ace9e213) run for https://github.com/conda-forge/numpy-feedstock/pull/238), so add some echos to see what's happening.
CC @isuruf @mattip

Fix pagefile sizing; add some echos on windows

---

recipe/install_cuda.bat
recipe/meta.yaml

Update to CUDA 11.5.1 and add CUDA 11.6
cc @jaimergp
Checklist

Add CUDA 11.5.1 & 11.6

---

.github/workflows/automerge.yml
.github/workflows/webservices.yml
conda-forge.yml

This PR moves the default branch from master to main. How to merge:
1. Merge this PR to master
2. In the settings, rename master to main
3. Submit an automated rerender command in another PR to make sure things are working. 
4. Bump the build number in the PR in 3 and merge.
5. Make sure that uploads.

[ci skip] move default branch from master to main

---

recipe/meta.yaml
recipe/run_conda_forge_build_setup_linux

Checklist
https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/183 introduced this bug. `CPU_COUNT` is unset on GH Actions, but we have a check later testing its value, which raises unbound variable due to `set -u`.

fix unbound variable error with CPU_COUNT on GH Actions

---

recipe/conda_forge_ci_setup/upload_or_check_non_existence.py
recipe/meta.yaml

Hopefully this will provide us a bit more context as to why a particular upload has failed. Also worth noting that this works fine with the `--quiet` option.
cc @mbargull
<hr>
Checklist
Fixes https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/215

Show traceback if upload fails

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/linux_64_c_compiler_version11cuda_compiler_versionNonepython3.10.____cpython.yaml
.ci_support/linux_64_c_compiler_version11cuda_compiler_versionNonepython3.11.____cpython.yaml
.ci_support/linux_64_c_compiler_version11cuda_compiler_versionNonepython3.8.____cpython.yaml
.ci_support/linux_64_c_compiler_version11cuda_compiler_versionNonepython3.9.____cpython.yaml
README.md
recipe/install_cuda.bat
recipe/meta.yaml

See https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/216#issuecomment-1341105124. cc: @jakirkham @m3vaz 
Checklist

Add missing (new) `cuda_profiler_api` component for CUDA 11.8 on Windows

---

.azure-pipelines/azure-pipelines-win.yml
.scripts/build_steps.sh
.scripts/run_osx_build.sh
recipe/conda_forge_ci_setup/feedstock_outputs.py
recipe/meta.yaml

Checklist
Needs:
- https://github.com/regro/conda-forge-metadata/pull/7
- https://github.com/regro/conda-forge-metadata/issues/11

use conda-forge-metadata for feedstock-outputs

---

recipe/cross_compile_support.sh

Trying to use CUDA 12 in https://github.com/conda-forge/arrow-cpp-feedstock/pull/1120, and it fails unsurprisingly because the branches here make it so.
Also picking up a minor comment improvement from #236

Allow cross-compilation with CUDA 12

---

recipe/meta.yaml
recipe/run_conda_forge_build_setup_win.bat

Fix setting HOST_PLATFORM

---

recipe/cross_compile_support.sh
recipe/meta.yaml

This amounts to about 2GB of useless stuff in the image.
<details>
<summary>selected large CUDA rpms from the install logs</summary>
```
curl -L -O https://developer.download.nvidia.com/compute/cuda/repos/rhel8/sbsa/cuda-nvcc-11-2-11.2.152-1.aarch64.rpm
100 57.8M  100 57.8M    0     0   108M      0 --:--:-- --:--:-- --:--:--  108M
curl -L -O https://developer.download.nvidia.com/compute/cuda/repos/rhel8/sbsa/cuda-nvrtc-11-2-11.2.152-1.aarch64.rpm
100 32.8M  100 32.8M    0     0  99.1M      0 --:--:-- --:--:-- --:--:-- 99.2M
curl -L -O https://developer.download.nvidia.com/compute/cuda/repos/rhel8/sbsa/libcublas-11-2-11.4.1.1043-1.aarch64.rpm
100  194M  100  194M    0     0   118M      0  0:00:01  0:00:01 --:--:--  118M
curl -L -O …
```

remove CUDA 11 rpm's after installing

---

recipe/cross_compile_support.sh
recipe/meta.yaml

In CUDA 11.4 `cuda-cccl` was split out from `cuda-cudart-devel`. As a result CCCL is not found when cross-compiling on CUDA 11.8. To address this, make sure CCCL is installed on CUDA 11.8 when cross-compiling.
<hr>
Checklist

Add CCCL for CUDA 11.8 cross-compilation

---

recipe/meta.yaml

@conda-forge/core, this can be merged into main, but feedstocks will only use the 3.* for now. After this is in and some testing is done, we can switch over to 4.* in conda-smithy.

4.0 with libmamba-solver

---

recipe/run_conda_forge_build_setup_win.bat

The logic here is to treat CUDA 12+ differently from previous CUDA versions. Specifically, for CUDA 12+ we
- do not download/extract any CUDA installer 
- do not need to set `CUDA_PATH` or update `PATH`
- but still need to set `CONDA_OVERRIDE_CUDA`
Tested in https://github.com/conda-forge/cupy-feedstock/pull/228.
cc: @conda-forge/cuda 
Checklist

Support CUDA 12 + Windows

---

recipe/meta.yaml
recipe/run_conda_forge_build_setup_win.bat

set CROSSCOMPILING_EMULATOR

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.scripts/build_steps.sh
.scripts/run_docker_build.sh
.scripts/run_osx_build.sh
.scripts/run_win_build.bat
README.md
recipe/cross_compile_support.sh
recipe/meta.yaml

The CUDA 12 cross-compilation check here is a no-op that specifically allows CUDA 12.0 to be used. However all CUDA 12.* versions support cross-compilation and none of them require the changes this script makes for CUDA 11 versions. So relax the check to allow any CUDA 12 version to work.
<hr>
Checklist

Relax CUDA 12 check in cross-compilation

---

recipe/meta.yaml

Removing the pinned version to allow it floating.
Checklist

Allow using the latest CalVer-based `conda-build`

---

recipe/conda_forge_ci_setup/feedstock_outputs.py
recipe/conda_forge_ci_setup/upload_or_check_non_existence.py
recipe/meta.yaml

Checklist
Stop using `conda_build.conda_interface`
`conda_build.conda_interface` is being deprecated.
`conda_build.conda_interface.get_index` (which is `conda.exports.get_index`)
is using the `conda.models.Dist` -> `conda.models.records.PackageRecord`
mapping. `Dist` class is legacy code that's being phased out, so avoid it.

Address conda build deprecations

---

recipe/conda_forge_ci_setup/feedstock_outputs.py
recipe/meta.yaml

Fixes https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/317
Checklist
xref: https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/305

Fix `conda_build.config.subdir` deprecation

---

recipe/conda_forge_ci_setup/upload_or_check_non_existence.py

Fixes https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/317
Checklist

Fix `conda_build.config.subdir` deprecation (pt. 2)

---

recipe/run_conda_forge_build_setup_win.bat

For feedstocks using
```
azure:
settings_win:
variables:
SET_PAGEFILE: "True"
```
we don't have a way to set the size (c.f. #160). Since the utility we're using to request the size of the pagefile allows setting both a minimum and a maximum, it shouldn't be an issue to increase the maximum a bit. Some compilations ([example](https://github.com/conda-forge/pygplates-feedstock/pull/20)) currently run out of memory even with the newest compiler & the 8GB swapfile & parallelization turned off. I'd like to see if this fixes it.

opportunistically set larger swap file on windows

---

recipe/conda_forge_ci_setup/build_utils.py
recipe/conda_forge_ci_setup/upload_or_check_non_existence.py
recipe/conda_forge_ci_setup/utils.py
recipe/meta.yaml

Also includes a small refactor to make the `determine_build_tool` function reusable.

disallow uploading from `rattler-build` feedstocks

---

recipe/meta.yaml

Checklist
This PR adds a strict upper bound to rattler-build-conda-compat to ensure that any semver incompatible changes will not break this package.

Add a strict upper-bound to rattler-build-conda-compat

---

recipe/meta.yaml

Checklist
Bump the upper bound of `rattler-build-conda-compat` to `2.0.0a0`. The API used from that package did not change between v0 and v1.

bump: rattler-build-conda-compat to 1.x

---

recipe/conda_forge_ci_setup/feedstock_outputs.py
recipe/conda_forge_ci_setup/utils.py
recipe/meta.yaml

Checklist
This PR fixes the case where the package is used outside conda-forge or conda_forge_output_validation is turned off.
xref: https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/338

fix: skip output validation if not on

---

.scripts/build_steps.sh
.scripts/run_osx_build.sh
.scripts/run_win_build.bat
recipe/conda_forge_ci_setup/feedstock_outputs.py
recipe/conda_forge_ci_setup/inspect_artifacts.py
recipe/conda_forge_ci_setup/upload_or_check_non_existence.py
recipe/conda_forge_ci_setup/utils.py
recipe/meta.yaml

This PR ensures we run output validation only on the packages we built.
closes #342 
closes #341

fix: ensure validation is run on correct files

---

recipe/conda_forge_ci_setup/inspect_artifacts.py
recipe/meta.yaml

This PR fixes a bug where the inspect command broke on staged recipes. I added a flag we can use there to inspect everything.
cc @jaimergp

fix: allow all distributions to be inspected

---

recipe/cross_compile_support.sh

This MR improves the way that `cross_compile_support.sh` attempts to install `{pkg}-cos7-{host_platform}` conda packages for packages listed in `yum_requirements.txt`.
`for pkg in $(cat recipe/yum_requirements.txt)` loops over words, which doesn't ignore comments properly, while `cat recipe/yum_requirements.txt | while read pkg` loops over lines, which should.
Checklist

Improve installing yum requirements with conda when cross compiling

---

recipe/conda_forge_ci_setup/feedstock_outputs.py
recipe/conda_forge_ci_setup/inspect_artifacts.py
recipe/conda_forge_ci_setup/utils.py
recipe/meta.yaml

This PR tries to again fix validation for downstreams. The code I wrote last time was imprecise. 
cc @h-vetinari and thank you to him for catching my bug!

fix: try again to exclude downstreams

---

recipe/conda_forge_ci_setup/build_utils.py
recipe/meta.yaml

Checklist
now that we have implemented all rattler-build lints checks and we have a working feedstock: https://github.com/conda-forge/jolt-physics-feedstock
I would like to uplift restrictions of uploading rattler-build to main channel.
Should be merged after release of: https://github.com/conda-forge/conda-smithy/pull/2037

feat: allow uploading on main channel for v1 recipes

---

recipe/cross_compile_support.sh
recipe/meta.yaml

Within `cuda-nvcc`'s RPM's `targets` directory, there is some content needed for `nvPTXCompiler`, which the Numba supporting CUDA 11 package, `ptxcompiler`, uses. This makes sure it is available when cross-compiling `ptxcompiler`.
As the Docker image and `conda-forge-ci-setup` limit content to the `targets` directory, the rest of the `cuda-nvcc` content will be ignored. This is for the best to ensure these other bits are not pulled in accidentally.
xref: https://github.com/conda-forge/ptxcompiler-feedstock/pull/38
<hr>
Checklist

Add `targets` content from `cuda-nvcc` for CUDA 11

---

recipe/cross_compile_support.sh
recipe/meta.yaml

This reverts PR: https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/356
We already are grabbing `nvcc` from the manifest and including it in the RPMs we will install on this line
https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/0e2048e39ef6bf91f04761f08b5510888a576567/recipe/cross_compile_support.sh#L113-L114
All adding it to `DEVELS` would have done is handle any remapping of the name in terms of manifest and package. However as the name is the same in both cases, this doesn't matter
IOW the aforementioned PR was effectively a no-op and what it was trying to accomplish had already been done. So while it causes no actual issues, it is probably best to clean this up to avoid confusion
This PR returns it to the prior state and bumps the patch version
<hr> …

Revert "Add `targets` content from `cuda-nvcc` for CUDA 11 (#356)"

---

recipe/conda_forge_ci_setup/utils.py
recipe/meta.yaml

The target platform was wrongly propagated in the conda build Config object in `arch` and `platform` instead of `host_arch` and `host_platform`. 
Sister PR: https://github.com/prefix-dev/rattler-build-conda-compat/pull/59
I encountered the issue when converting a feedstock to rattler at https://github.com/conda-forge/xformers-feedstock/pull/33

[rattler-build] Correctly propagate target platform to `host_{arch|platform}`

---

recipe/cross_compile_support.sh
recipe/meta.yaml

use the same glibc version as the docker image for cross

---

recipe/cross_compile_support.sh
recipe/meta.yaml

I'm running into a possible regression in QEMU (c.f. https://github.com/conda-forge/ctng-compilers-feedstock/pull/147), and I cannot go back to the last passing CI run to see which version was used. So ensure that the version gets logged.

show qemu version when running cross_compile_support.sh

---

recipe/cross_compile_support.sh
recipe/meta.yaml
recipe/run_conda_forge_build_setup_linux

fix cross compile with pixi

---

recipe/meta.yaml
recipe/run_conda_forge_build_setup_win.bat

For debugging (or preparing bug reports to conda-build), it's convenient to be able to search for `conda info` in the logs. However, currently the ci-setup on windows only shows the output of those calls, but not the calls themselves (in contrast to unix).
Fix this.

show `conda {info,config,list}` commands being called

---

recipe/cross_compile_support.sh

Fixes #395 with an assumption that CUDA packages will maintain this functionality.
CC @billysuh7 @h-vetinari

Remove upper bound on CUDA version check

---

recipe/cross_compile_support.sh
recipe/meta.yaml

Extend @msarahan's improvements from PR ( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/396 ) to one more last CUDA cross-compilation CI setup error message.
<hr> 
Checklist

Generalize one last CUDA cross-compilation CI setup error message
